シス管の全体方針を書きました
ritscc/soukai-2021-2 pull request #68
Opened 2022-02-15 14:01 UTC by hane0817

fix #50

2022-02-17 08:38 UTC, kyochn requested changes
僕の説明が雑だったのもあり，指摘したい点が色々ありますがまず以下の点を直してきてください．
- 内容を見る限りこれは総括です．方針を書いてきてください．
- 総会文書は堅めのしっかりした文書を作る必要があります．なので話し合い議事録の丸写しをするのではなく，しっかりとした文章を書いてきてください．正しく句読点を用い，ハンドルネームなどは書かないようにしましょう．大学のレポートや論文くらいのつもりで書いてください．
- シス管の全体方針は会内方針と局内方針だけです．引き継ぎ方針や勉強会方針などは含まれません
- 文頭に文責\writtenBy{\systemStaff}が来るようにしてください
- LaTeXのコメントアウトは%を使います

以上

2022-02-17 09:45 UTC, thetaleisalsowhite commented
まずは、きょうすけ君の言う通り。
今までの年度の内容を遡ってみることもできるので、雰囲気を掴んでから書き直すのがよろしいかと。

2022-02-18 01:58 UTC, lufeee approved these changes

2022-02-18 06:22 UTC, kyochn reviewed
内容は大体OKです
あとはunagiの指摘通り直してください
あと余談ですけど．LaTeXは空行付けない限り改行されないので，適宜改行した方が元文書読みやすいし編集しやすいです

2022-02-19 11:11 UTC, kyochn approved these changes

2022-02-23 12:35 UTC, merged