研推：プロジェクト総括を執筆
ritscc/soukai-2021-2 pull request #90
Opened 2022-02-19 12:22 UTC by RosesAndViolets

Fix#3：プロジェクト総括を執筆

2022-02-19 12:30 UTC, RosesAndViolets commented
嘘、Fix＃１１だった。
まちがえました。

2022-02-20 06:01 UTC, ygkn requested changes
コメントしたとこだけ！

2022-02-20 06:01 UTC, ygkn commented on src/soukatsu/kensui/02_project.tex
> +上回性会議で解散の是非を話し合うべきであったが，本局でその手続きをせずに解散にさせてしまった．
```suggestion
上回生会議で解散の是非を話し合うべきであったが，本局でその手続きをせずに解散にさせてしまった．
```
上回性→上回生

2022-02-20 06:01 UTC, ygkn commented on src/soukatsu/kensui/02_project.tex
> +入会費の支払い記録以上に本会の活動に参加する会員が把握できるようなリストを次回から取り入れることが提案された．
```suggestion
入会費の支払い記録以上に本会の活動に参加する会員が把握できるようなリストを次回から取り入れる．
```

`ことが提案された` は冗長なのでいらないかも？

2022-02-20 06:01 UTC, ygkn commented on src/soukatsu/kensui/02_project.tex
> +入会費の支払い記録以上に本会の活動に参加する会員が把握できるようなリストを次回から取り入れることが提案された．
`入会費の支払い記録以上に` はわかりにくいかも

`入会費の支払い記録とは別に` という意味？

2022-02-20 06:01 UTC, ygkn commented on src/soukatsu/kensui/02_project.tex
> +これらの定例会議，LT，プロジェクトの参加頻度が分からず，会員のプロジェクト管理に難航したため，
```suggestion
このような会員らのプロジェクトを含む活動の参加頻度が分からず，会員のプロジェクト管理に難航したため，
```

ここはプロジェクト管理の話なので、プロジェクト活動を主に書いたほうがいいかも

2022-02-20 06:01 UTC, ygkn commented on src/soukatsu/kensui/02_project.tex
> +発表ができないプロジェクト班もあったが，
途中？

2022-02-20 06:01 UTC, ygkn commented on src/soukatsu/kensui/02_project.tex
> +週報の提出が遅延したプロジェクトもあったが，班員を通して正常に活動していることが確認できていたため，
```suggestion
週報の提出が遅延したプロジェクトが存在したが，班員を通して正常に活動していることが確認できていたため，
```

`も` は追加なのでこっちのが自然かも

2022-02-20 06:01 UTC, ygkn commented on src/soukatsu/kensui/02_project.tex
> +全てのプロジェクト班が報告書を提出し，プロジェクト活動の成果発表の際に参加者全員でレビューし，
```suggestion
全てのプロジェクト班が報告書を提出し，成果発表に間に合わなかったプロジェクトを除いて，
プロジェクト活動の成果発表の際に参加者全員でレビューし，
```

2022-02-20 10:56 UTC, thetaleisalsowhite approved these changes
八木ちゃんの言及以外はOKだと思います!!
マージに3人必要なのでApproveしちゃいます!!

2022-02-20 13:13 UTC, fukada6280 approved these changes
やぎちゃんの指摘しっかり直してくれれば問題ないです！

2022-02-22 09:59 UTC, ygkn approved these changes
OK!
さすが！

2022-02-23 12:22 UTC, merged